#!/bin/bash

# Demo script to showcase the restored UI feedback feature
# This script shows the interactive flow with the Azure Portal integration

echo "🔍 AppInsights Detective - UI Feedback Feature Demo"
echo "=================================================="
echo ""
echo "This demo shows the restored 'Open in Azure Portal' feature"
echo "that was lost during architecture refactoring."
echo ""
echo "Features demonstrated:"
echo "✅ Interactive session with step-by-step guidance"
echo "✅ Query mode selection (Smart/Review/Raw)"
echo "✅ Multi-choice action menu including:"
echo "   🚀 Execute Query"
echo "   📖 Explain Query"
echo "   🌐 Open in Azure Portal (RESTORED!)"
echo "   🔄 Regenerate Query"
echo "   ✏️ Edit Query"
echo "   📜 View History"
echo ""
echo "To test the restored feature:"
echo "1. Run: aidx --interactive"
echo "2. Ask: 'show me errors from last hour'"
echo "3. Choose: 'Review Mode'"
echo "4. Select: '🌐 Open in Azure Portal'"
echo ""
echo "The portal option will appear when:"
echo "- External execution service is available"
echo "- Azure configuration is properly set (tenant, subscription, resource group, app name)"
echo ""
echo "Demo completed! The UI feedback feature has been successfully restored."